### ISSUE TITLE
Relax version bounds

### ISSUE THREAD

**Issue by Josef-Thorne-A** [cdepillabout/focuslist#5]
Proper version bounding in the `focuslist.cabal` file is essential. The curent version bounding is very conservative, though it appears to work. 

The version bounds should reflect reality as best as possible. They are currently very strict, this should be amended.

**Comment by cdepillabout** [comment]
I'd also be fine with removing the upper bounds because it is generally a lot of work to keep them up-to-date.

In general, the goal is to keep the `focuslist` library in Stackage, so it should *always* work with the latest version of its dependencies.  I think in general we should get notifications from the Stackage curators when this isn't happening.

**Comment by cdepillabout** [comment]
Also, it would be great to make sure Travis is succeeding.  It currently looks like it is failing:

https://travis-ci.org/cdepillabout/focuslist/builds/462465735

**Comment by cdepillabout** [comment]
@Grendel-Grendel-Grendel In general, whenever you are changing something that could cause `focuslist` not to be able to compile (so really anything other than documentation), could you create a PR instead of committing directly to `master`?

That way we can make sure not to merge anything that causes travis to fail.

**Comment by Josef-Thorne-A** [comment]
Sorry about that, I made some faulty assumptions. It's a bit of a learning process for me here. Thanks for being patient. I'll get to fixing it right now.

**Comment by cdepillabout** [comment]
@Grendel-Grendel-Grendel No problem, thanks for fixing it!

**Comment by Josef-Thorne-A** [comment]
Focuslist should now be in stackage as well if I’m not mistaken.

**Comment by cdepillabout** [comment]
It looks like all the upper bounds have been removed, so hopefully that fixes this issue.
